<h1><?php echo $this->getHelloWorldText(); ?></h1>


<div id="vendor-filter-div">
    <form class="form vendor-filter">
        <fieldset class="fieldset">
            <div class="field name required">
                <label class="label" for="address"><span><?php  echo __('Address') ?></span></label>
                <div class="control">
                    <input name="address" id="address" title="<?php  echo __('Address') ?>" class="input-text" type="text" />
                </div>
            </div>
            <div class="field name">
                <label class="label" for="distance"><span><?php  echo __('Distance') ?></span></label>
                <div class="control">
                    <select  name="distance" id="distance" title="<?php  echo __('Distance') ?>" >
                        <option value="1">1km</option>
                        <option value="5">5km</option>
                        <option value="10">10km</option>
                        <option value="50">50km</option>
                    </select>
                </div>
            </div>
            <div class="field companyname">
                <label class="label" for="company"><span><?php  echo __('Company name') ?></span></label>
                <div class="control">
                    <input name="company" id="company" title="<?php  echo __('Company') ?>" class="input-text" type="text"/>
                </div>

            </div>

        </fieldset>
    </form>
    <div>
        <button  title="<?php  echo __('Submit') ?>" onclick="getLatLongFromAddress()" class="action submit primary" id="custom_btn">
            <span><?php  echo __('Submit') ?></span>
        </button>
    </div>
</div>
<div id="map-div"  ></div>

<div id="vendor-info-div" ></div>

<script>
    setListOfVendors(<?php echo $this->getVendorsJSON(); ?>);
</script>
<script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDxyJ5-9IVUtqzfCyrY_uRRKNK3Ftg_On0&callback=initMap"
></script>
