<h1><?php echo $this->getHelloWorldText(); ?></h1>


<div id="vendor-filter-div">
    <form class="form vendor-filter">
        <fieldset class="fieldset">
            <div class="field name required">
                <label class="label" for="address"><span><?php  echo __('Address') ?></span></label>
                <div class="control">
                    <input name="address" id="address" title="<?php  echo __('Address') ?>" class="input-text" type="text" />
                </div>
            </div>
            <div class="field name">
                <label class="label" for="distance"><span><?php  echo __('Distance') ?></span></label>
                <div class="control">
                    <select  name="distance" id="distance" title="<?php  echo __('Distance') ?>" >
                        <option value="1">1km</option>
                        <option value="5">5km</option>
                        <option value="10">10km</option>
                        <option value="50">50km</option>
                    </select>
                </div>
            </div>
            <div class="field companyname">
                <label class="label" for="company"><span><?php  echo __('Company name') ?></span></label>
                <div class="control">
                    <input name="company" id="company" title="<?php  echo __('Company') ?>" class="input-text" type="text"/>
                </div>

            </div>

        </fieldset>
    </form>
    <div>
        <button  title="<?php  echo __('Submit') ?>" onclick="getLatLongFromAddress()" class="action submit primary" id="custom_btn">
            <span><?php  echo __('Submit') ?></span>
        </button>
    </div>
</div>
<div id="map-div" style="height: 400px; width: 80%;" ></div>

<div id="vendor-info-div" style="height: 400px; width: 80%;" ></div>
<script>
    let listOfVendors = <?php echo $this->getVendorsJSON(); ?>;
    let map;
    let markers = [];
    let myPos;


    function initMap() {
        let defaultMapLocation = { lat: 44.0279099 , lng:20.912623 }

        map = new google.maps.Map(document.getElementById("map-div"), {
            zoom: 6,
            center: defaultMapLocation,
        });
        for(let i=0; i<listOfVendors.items.length; i++) {
            addMarker(listOfVendors.items[i]);
        }
    }

    function getLatLongFromAddress() {
        let address = document.getElementById('address').value;
        let company = document.getElementById('company').value;
        if(address.length === 0 && company.length === 0)
            return;
        if(address.length > 0)
        {
            console.log("address");
            let addressEncoded = encodeURI(address);
            var s = document.createElement('script');
            s.src = 'http://nominatim.openstreetmap.org/search?json_callback=cb&format=json&q='+ addressEncoded +'&addressdetails=1';
            document.getElementsByTagName('head')[0].appendChild(s);
        }
        else
        {
            console.log("company");
            filterByName(company);
        }
    }

    function addMarker(vendor){
        const marker = new google.maps.Marker({
            position: { lat: Number(vendor.lat), lng: Number(vendor.long) },
            map: map,
        });

        marker.addListener('click', () => {
            var elementVendorInfo = document.getElementById("vendor-info-div");
            if(vendor.premium === "1") {
                elementVendorInfo.innerText = '';
                elementVendorInfo.appendChild(createTable(vendor));

            } else {
                elementVendorInfo.innerText = "";
            }
        });
        markers.push(marker);
    }

    function filterByName(companyName){
        setMapOnAll(null);
        markers = [];
        for(let i=0; i<listOfVendors.items.length; i++){
            if(listOfVendors.items[i].name.toLowerCase().includes(companyName.toLowerCase())) {
                addMarker(listOfVendors.items[i]);
            }
        }
    }

    function cb(data) {
        if(data.size === 0)
            return;
        const image = "http://maps.google.com/mapfiles/ms/icons/blue-dot.png"
        myPos = { lat: Number(data[0].lat), lng: Number(data[0].lon) };
        console.log(myPos);
        setMapOnAll(null);
        markers = [];
        myPositionMarker = new google.maps.Marker({
                position: myPos,
             map: map,
            icon: image
        });
        markers.push(myPositionMarker);
        filterVendorsOnMap();
    }



    function filterVendorsOnMap() {
        let inputSelectDistance = document.getElementById('distance');
        let distanceInKm = inputSelectDistance.value;
        let company = document.getElementById('company').value;
        for(let i=0; i<listOfVendors.items.length; i++){
            markerPos = { lat: Number(listOfVendors.items[i].lat), lng: Number(listOfVendors.items[i].long) };
            if(getDistance(myPos, markerPos) < distanceInKm*1000) {
                addMarker(listOfVendors.items[i]);
            }

        }
    }

    function createTable(vendorDetails) {
        let tbl = document.createElement('table');
        tbl.id = 'info-table';
        tbl.style.width = '500px';
        tbl.style.border = '1px solid black';
        let tbdy = document.createElement('tbody');
        let trName = document.createElement('tr');
        let tdLblName = document.createElement('td');
        let tdName = document.createElement('td');
        tdName.innerText = vendorDetails.name;
        tdLblName.innerText ='Vendor name: ';
        trName.appendChild(tdLblName);
        trName.appendChild(tdName);

        let trAddress = document.createElement('tr');
        let tdLblAddress = document.createElement('td');
        let tdAddress = document.createElement('td')
        tdAddress.innerText = vendorDetails.address;
        tdLblAddress.innerText ='Address : ';
        trAddress.appendChild(tdLblAddress);
        trAddress.appendChild(tdAddress);

        let trPostalCode = document.createElement('tr');
        let tdLblPostalCode = document.createElement('td');
        let tdPostalCode = document.createElement('td')
        tdPostalCode.innerText = vendorDetails.postal_code + ' ' + vendorDetails.city;
        tdLblPostalCode.innerText ='Postal code & city : ';
        trPostalCode.appendChild(tdLblPostalCode);
        trPostalCode.appendChild(tdPostalCode);

        tbdy.appendChild(trName);
        tbdy.appendChild(trAddress);
        tbdy.appendChild(trPostalCode);
        tbl.appendChild(tbdy);
        return tbl;

    }

    function setMapOnAll(map) {
        for (let i = 0; i < markers.length; i++) {
            markers[i].setMap(map);
        }
    }
    function rad(x) {
        return x * Math.PI / 180;
    }
     function getDistance(p1, p2) {
        let R = 6378137; // Earth’s mean radius in meter
         let dLat = rad(p2.lat - p1.lat);
         let dLong = rad(p2.lng - p1.lng);
         let a = Math.sin(dLat / 2) * Math.sin(dLat / 2) +
            Math.cos(rad(p1.lat)) * Math.cos(rad(p2.lat)) *
            Math.sin(dLong / 2) * Math.sin(dLong / 2);
         let c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
         let d = R * c;
        return d; // returns the distance in meter
    }

</script>



<style>
 #vendor-filter-div{
     border: solid 3px darkred;
     margin: 20px;
     padding: 20px;
     width: 70%;
 }

 #info-table {
     width: 500px;
     border: 1px solid black;
     margin: 20px;
     background-color: lightgray;
     color: black;
 }



</style>
<script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDxyJ5-9IVUtqzfCyrY_uRRKNK3Ftg_On0&callback=initMap&libraries=&v=weekly"
></script>
